# Generated by Django 2.1 on 2018-08-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.CharField(default='Subscriptions :[]', max_length=5000),
        ),
    ]
