# Generated by Django 2.1 on 2018-08-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180803_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.CharField(default='{Subscriptions :[]}', max_length=5000),
        ),
    ]
