# Generated by Django 2.1 on 2018-08-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180803_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.CharField(default='{"Subscriptions" :[None]}', max_length=5000),
        ),
    ]
